// AUTO-GENERATED by scripts/parse-entities.js — do not edit manually.
// To update: edit entities.md then run `npm run build` (or `node scripts/parse-entities.js`).

import type { AgentId } from "@/components/AgentSystem";

export type GenException = {
  id: string; title: string; confidence: number; status: "Pending";
  entity: string; kyc: string; category: string;
  flagText: string; narrative: string;
  reasoningSteps: string[]; evidenceRationale: string;
  evidence: { name: string; sub: string }[];
  acceptability: string;
  resolutions: {
    id: string; title: string; desc: string; recommended?: boolean;
    agents: AgentId[]; agentLabel: string;
    postRunSummary: string;
    updates: { attr: string; before: string; after: string }[];
  }[];
};

export const GENERATED_EXCEPTIONS: GenException[] = [
  {
    id: "gen1_1", title: "US Registration Number Mismatch", confidence: 90, status: "Pending",
    entity: "Long Focus Capital Management, LLC", kyc: "KYC-30215", category: "Registration & Compliance",
    flagText: "US Registration Number: 801-12345 (self-reported) (Source A · Client Onboarding Form) vs 801-67890 (retrieved 2026-05-20) (Source B · SEC IAPD (Form ADV Part 1A)).",
    narrative: "The client-provided CRD number (801-12345) maps to a separate entity, \"Long Focus Capital LLC\" — without \"Management\" — in IAPD. The legal name and registered address on the onboarding form match the entity registered under 801-67890. This is most likely a transcription error on the onboarding form and can be corrected with regulator data taken as authoritative.",
    reasoningSteps: [
      "SEC IAPD is the system of record for RIA registration numbers under KYC Policy §3.1.",
      "Legal entity name and principal address on Form ADV match the client onboarding form exactly.",
      "The client-provided number resolves in IAPD but to a different legal entity with a different address — supporting the transcription-error hypothesis rather than a substantive conflict.",
    ],
    evidenceRationale: "Source A · Client Onboarding Form and Source B · SEC IAPD (Form ADV Part 1A) are the primary evidence sources.",
    evidence: [
      { name: "Source A · Client Onboarding Form", sub: "801-12345 (self-reported)" },
      { name: "Source B · SEC IAPD (Form ADV Part 1A)", sub: "801-67890 (retrieved 2026-05-20)" },
    ],
    acceptability: "US Registration Number Mismatch requires analyst review and resolution before case closure.",
    resolutions: [
      {
        id: "r1", title: "Run SEC-ADV-Verification-Agent to confirm match", desc: "Run SEC-ADV-Verification-Agent to confirm match, update the field to 801-67890, and log discrepancy in audit trail.",
        recommended: true,
        agents: ["regulatory", "document", "audit"] as AgentId[],
        agentLabel: "Run SEC-ADV-Verification-Agent to confirm match",
        postRunSummary: "Run SEC-ADV-Verification-Agent to confirm match. Case status updated.",
        updates: [
          { attr: "Case Status", before: "Open · Pending analyst action", after: "In Progress" },
        ],
      },
      {
        id: "r2", title: "Accept client-provided number with Senior Analyst override", desc: "Accept client-provided number with Senior Analyst override and documented rationale.",
        agents: ["regulatory", "document", "audit"] as AgentId[],
        agentLabel: "Accept client-provided number with Senior Analyst override",
        postRunSummary: "Accept client-provided number with Senior Analyst override. Case status updated.",
        updates: [
          { attr: "Case Status", before: "Open · Pending analyst action", after: "Escalated" },
        ],
      },
      {
        id: "r3", title: "Return to client via Relationship Manager for", desc: "Return to client via Relationship Manager for correction.",
        agents: ["regulatory", "document", "audit"] as AgentId[],
        agentLabel: "Return to client via Relationship Manager for",
        postRunSummary: "Return to client via Relationship Manager for. Case status updated.",
        updates: [
          { attr: "Case Status", before: "Open · Pending analyst action", after: "Escalated" },
        ],
      },
    ],
  },
  {
    id: "gen1_2", title: "Outstanding LEI Code", confidence: 90, status: "Pending",
    entity: "Long Focus Capital Management, LLC", kyc: "KYC-30215", category: "Registration & Compliance",
    flagText: "LEI Code: No active LEI under entity legal name (Source A · GLEIF Registry) vs Not provided (Source B · Client Onboarding Form).",
    narrative: "No active LEI was found on GLEIF under the entity's legal name or against its SEC registration number. For an RIA with \\$2.4B AUM, an LEI is typically expected for swap and derivatives counterparty reporting under EMIR and Dodd-Frank. The absence may indicate the client does not transact in reportable instruments, or that LEI registration has lapsed or is pending.",
    reasoningSteps: [
      "LEI is not a CIP requirement and does not block case closure under FinCEN CDD Rule.",
      "LEI is required for any EMIR- or Dodd-Frank-reportable derivative or swap activity, which is plausible given AUM.",
      "GLEIF returned no match against either legal name or SEC registration number, indicating no LEI has ever been issued (vs. lapsed).",
    ],
    evidenceRationale: "Source A · GLEIF Registry and Source B · Client Onboarding Form are the primary evidence sources.",
    evidence: [
      { name: "Source A · GLEIF Registry", sub: "No active LEI under entity legal name" },
      { name: "Source B · Client Onboarding Form", sub: "Not provided" },
    ],
    acceptability: "Outstanding LEI Code requires analyst review and resolution before case closure.",
    resolutions: [
      {
        id: "r1", title: "Request LEI from client via portal with", desc: "Request LEI from client via portal with templated outreach; defer with conditional approval if client confirms no reportable activity.",
        recommended: true,
        agents: ["regulatory", "document", "audit"] as AgentId[],
        agentLabel: "Request LEI from client via portal with",
        postRunSummary: "Request LEI from client via portal with. Case status updated.",
        updates: [
          { attr: "Case Status", before: "Open · Pending analyst action", after: "In Progress" },
        ],
      },
      {
        id: "r2", title: "Initiate Broad Search Agent across alternative identifier", desc: "Initiate Broad Search Agent across alternative identifier registries (GMEI Utility, KY3P).",
        agents: ["regulatory", "document", "audit"] as AgentId[],
        agentLabel: "Initiate Broad Search Agent across alternative identifier",
        postRunSummary: "Initiate Broad Search Agent across alternative identifier. Case status updated.",
        updates: [
          { attr: "Case Status", before: "Open · Pending analyst action", after: "Escalated" },
        ],
      },
      {
        id: "r3", title: "Flag for re-verification at 30 days", desc: "Flag for re-verification at 30 days.",
        agents: ["regulatory", "document", "audit"] as AgentId[],
        agentLabel: "Flag for re-verification at 30 days",
        postRunSummary: "Flag for re-verification at 30 days. Case status updated.",
        updates: [
          { attr: "Case Status", before: "Open · Pending analyst action", after: "Escalated" },
        ],
      },
    ],
  },
  {
    id: "gen1_3", title: "Principal Place of Business Mismatch", confidence: 88, status: "Pending",
    entity: "Long Focus Capital Management, LLC", kyc: "KYC-30215", category: "Address Verification",
    flagText: "Principal Address: 123 Main Street, New York, NY 10001 (Source A · Corporate Website) vs 456 Broad Avenue, New York, NY 10005 (Source B · Form ADV Filing (SEC)).",
    narrative: "Two of three sources (Form ADV and client onboarding form) agree on 456 Broad Avenue. The corporate website shows 123 Main Street, likely a secondary office or stale content. Per KYC Policy §3.5 the regulatory filing supersedes marketing material for address determination.",
    reasoningSteps: [
      "KYC Policy §3.5 establishes a hierarchy in which regulatory filings outrank corporate website content for address verification.",
      "The Form ADV address matches the address self-reported on the client onboarding form, providing two corroborating sources.",
      "The website discrepancy is consistent with a secondary office or unmaintained content rather than a substantive change of principal place of business.",
    ],
    evidenceRationale: "Source A · Corporate Website and Source B · Form ADV Filing (SEC) are the primary evidence sources.",
    evidence: [
      { name: "Source A · Corporate Website", sub: "123 Main Street, New York, NY 10001" },
      { name: "Source B · Form ADV Filing (SEC)", sub: "456 Broad Avenue, New York, NY 10005" },
    ],
    acceptability: "Principal Place of Business Mismatch requires analyst review and resolution before case closure.",
    resolutions: [
      {
        id: "r1", title: "Accept Form ADV address (456 Broad Avenue)", desc: "Accept Form ADV address (456 Broad Avenue) as authoritative; matches client form.",
        recommended: true,
        agents: ["document", "regulatory", "audit"] as AgentId[],
        agentLabel: "Accept Form ADV address (456 Broad Avenue)",
        postRunSummary: "Accept Form ADV address (456 Broad Avenue). Case status updated.",
        updates: [
          { attr: "Case Status", before: "Open · Pending analyst action", after: "In Progress" },
        ],
      },
      {
        id: "r2", title: "Run Geolocation \\& Business Directory Check (D\\&B", desc: "Run Geolocation \\& Business Directory Check (D\\&B, Google Places) as a tiebreaker before acceptance.",
        agents: ["document", "regulatory", "audit"] as AgentId[],
        agentLabel: "Run Geolocation \\& Business Directory Check (D\\&B",
        postRunSummary: "Run Geolocation \\& Business Directory Check (D\\&B. Case status updated.",
        updates: [
          { attr: "Case Status", before: "Open · Pending analyst action", after: "Escalated" },
        ],
      },
      {
        id: "r3", title: "Request clarification from client", desc: "Request clarification from client.",
        agents: ["document", "regulatory", "audit"] as AgentId[],
        agentLabel: "Request clarification from client",
        postRunSummary: "Request clarification from client. Case status updated.",
        updates: [
          { attr: "Case Status", before: "Open · Pending analyst action", after: "Escalated" },
        ],
      },
    ],
  },
  {
    id: "gen1_4", title: "Missing Compliance Officer Attestation", confidence: 92, status: "Pending",
    entity: "Long Focus Capital Management, LLC", kyc: "KYC-30215", category: "Governance & Controls",
    flagText: "Compliance Officer Name: Sarah Chen (Chief Compliance Officer) (Source A · Form ADV Schedule A) vs Not listed (Source B · Client Submitted Documents).",
    narrative: "The Chief Compliance Officer's identity is known via Form ADV Schedule A. What is missing is a signed attestation, not the name itself. A templated DocuSign request to the named CCO is the most direct path.",
    reasoningSteps: [
      "CCO identity is independently verified through the regulatory filing.",
      "The gap is an artifact (signed attestation) rather than an unknown attribute.",
      "Direct request to the named officer is faster than relationship-manager-mediated outreach for a known administrative item.",
    ],
    evidenceRationale: "Source A · Form ADV Schedule A and Source B · Client Submitted Documents are the primary evidence sources.",
    evidence: [
      { name: "Source A · Form ADV Schedule A", sub: "Sarah Chen (Chief Compliance Officer)" },
      { name: "Source B · Client Submitted Documents", sub: "Not listed" },
    ],
    acceptability: "Missing Compliance Officer Attestation requires analyst review and resolution before case closure.",
    resolutions: [
      {
        id: "r1", title: "Generate pre-filled DocuSign attestation form and send", desc: "Generate pre-filled DocuSign attestation form and send to Sarah Chen.",
        recommended: true,
        agents: ["document", "outreach", "audit"] as AgentId[],
        agentLabel: "Generate pre-filled DocuSign attestation form and send",
        postRunSummary: "Generate pre-filled DocuSign attestation form and send. Case status updated.",
        updates: [
          { attr: "Case Status", before: "Open · Pending analyst action", after: "In Progress" },
        ],
      },
      {
        id: "r2", title: "Accept ADV-listed CCO name with a conditional", desc: "Accept ADV-listed CCO name with a conditional flag for the attestation to follow.",
        agents: ["document", "outreach", "audit"] as AgentId[],
        agentLabel: "Accept ADV-listed CCO name with a conditional",
        postRunSummary: "Accept ADV-listed CCO name with a conditional. Case status updated.",
        updates: [
          { attr: "Case Status", before: "Open · Pending analyst action", after: "Escalated" },
        ],
      },
      {
        id: "r3", title: "Escalate to client relationship team", desc: "Escalate to client relationship team.",
        agents: ["document", "outreach", "audit"] as AgentId[],
        agentLabel: "Escalate to client relationship team",
        postRunSummary: "Escalate to client relationship team. Case status updated.",
        updates: [
          { attr: "Case Status", before: "Open · Pending analyst action", after: "Escalated" },
        ],
      },
    ],
  },
  {
    id: "gen1_5", title: "Beneficial Ownership Not Identified", confidence: 85, status: "Pending",
    entity: "Long Focus Capital Management, LLC", kyc: "KYC-30215", category: "Beneficial Ownership",
    flagText: "25%+ Beneficial Owner: Long Focus Holdings LLC (100%) — entity, not individual (Source A · Form ADV Schedule A) vs Chain terminates at Long Focus Holdings LLC; no further public data (Source B · Public Registry Traversal).",
    narrative: "The ownership chain terminates at a Delaware holding company with no publicly disclosed ownership. The FinCEN CDD Rule (31 CFR 1010.230) requires identification of natural-person beneficial owners at the 25%+ threshold, so this case cannot close until a natural person is identified or the client provides a FinCEN BOI report.",
    reasoningSteps: [
      "The 25% beneficial ownership threshold is a regulatory requirement, not a policy preference — case closure is blocked.",
      "Delaware does not require public ownership disclosure for LLCs, so further traversal through public sources alone is unlikely to succeed.",
      "Paid registry access (LexisNexis, Sayari) may resolve ownership without client outreach, but client BOI report is the authoritative source.",
    ],
    evidenceRationale: "Source A · Form ADV Schedule A and Source B · Public Registry Traversal are the primary evidence sources.",
    evidence: [
      { name: "Source A · Form ADV Schedule A", sub: "Long Focus Holdings LLC (100%) — entity, not individual" },
      { name: "Source B · Public Registry Traversal", sub: "Chain terminates at Long Focus Holdings LLC; no further publ" },
    ],
    acceptability: "Beneficial Ownership Not Identified requires analyst review and resolution before case closure.",
    resolutions: [
      {
        id: "r1", title: "Issue formal FinCEN BOI report request to", desc: "Issue formal FinCEN BOI report request to client with 7-day SLA.",
        recommended: true,
        agents: ["beneficial-owner", "outreach", "audit"] as AgentId[],
        agentLabel: "Issue formal FinCEN BOI report request to",
        postRunSummary: "Issue formal FinCEN BOI report request to. Case status updated.",
        updates: [
          { attr: "Case Status", before: "Open · Pending analyst action", after: "In Progress" },
        ],
      },
      {
        id: "r2", title: "Run Ownership Resolution Agent against paid registries", desc: "Run Ownership Resolution Agent against paid registries (LexisNexis, Sayari) to attempt resolution before client outreach.",
        agents: ["beneficial-owner", "outreach", "audit"] as AgentId[],
        agentLabel: "Run Ownership Resolution Agent against paid registries",
        postRunSummary: "Run Ownership Resolution Agent against paid registries. Case status updated.",
        updates: [
          { attr: "Case Status", before: "Open · Pending analyst action", after: "Escalated" },
        ],
      },
      {
        id: "r3", title: "Escalate to the Enhanced Due Diligence team", desc: "Escalate to the Enhanced Due Diligence team.",
        agents: ["beneficial-owner", "outreach", "audit"] as AgentId[],
        agentLabel: "Escalate to the Enhanced Due Diligence team",
        postRunSummary: "Escalate to the Enhanced Due Diligence team. Case status updated.",
        updates: [
          { attr: "Case Status", before: "Open · Pending analyst action", after: "Escalated" },
        ],
      },
    ],
  },
  {
    id: "gen2_1", title: "Risk Rating", confidence: 78, status: "Pending",
    entity: "BROOKFIELD ASSET MANAGEMENT PIC US, LLC", kyc: "KYC-30216", category: "Classification & Risk",
    flagText: "Risk Rating: High – Due to adding an optional field ownership country (Source A · Due Diligence) vs Low – Initial classification during the time of RR (Source B · Internal records).",
    narrative: "Given the change in risk rating triggered during onboarding due to the addition of Cayman-domiciled ownership entities, there is a discrepancy between the initial risk classification (Low) and the current system-generated classification (High). The client has remained cooperative throughout the process, and the ultimate parent entity is a well-established and known client to the firm. The current ownership structure update has led to additional drilldown requirements, which may not align with jurisdiction-specific risk interpretation.",
    reasoningSteps: [
      "The client was previously classified as Low Risk under another division's UK policy closure in January 2026, and no material adverse factors were identified at that time.",
      "The introduction of Cayman-domiciled ownership entities (which is an optional task during onboarding) has systematically triggered a High Risk classification, although Cayman jurisdiction alone is not considered a high-risk trigger under UK standards.",
      "The ultimate beneficial owner is a reputable and known entity, reducing overall risk concerns from a KYC standpoint.",
      "The client has demonstrated full cooperation, and late-stage changes to ownership drilldown requirements (e.g., shifting from 25% to 10%) would negatively impact client experience.",
    ],
    evidenceRationale: "Source A · Due Diligence and Source B · Internal records are the primary evidence sources.",
    evidence: [
      { name: "Source A · Due Diligence", sub: "High – Due to adding an optional field ownership country" },
      { name: "Source B · Internal records", sub: "Low – Initial classification during the time of RR" },
    ],
    acceptability: "Risk Rating requires analyst review and resolution before case closure.",
    resolutions: [
      {
        id: "r1", title: "Threshold Alignment", desc: "Threshold Alignment: Seek confirmation from Compliance to proceed with a 25% ownership drilldown threshold, considering:",
        recommended: true,
        agents: ["regulatory", "risk-scoring", "audit"] as AgentId[],
        agentLabel: "Threshold Alignment",
        postRunSummary: "Threshold Alignment. Case status updated.",
        updates: [
          { attr: "Case Status", before: "Open · Pending analyst action", after: "In Progress" },
        ],
      },
      {
        id: "r2", title: "Policy Exception / Risk Revalidation", desc: "Policy Exception / Risk Revalidation: Request a risk rating override or exception from compliance to align the entity back to Low/Medium risk, supported by:",
        agents: ["regulatory", "risk-scoring", "audit"] as AgentId[],
        agentLabel: "Policy Exception / Risk Revalidation",
        postRunSummary: "Policy Exception / Risk Revalidation. Case status updated.",
        updates: [
          { attr: "Case Status", before: "Open · Pending analyst action", after: "Escalated" },
        ],
      },
      {
        id: "r3", title: "Stakeholder Escalation (if required)", desc: "Stakeholder Escalation (if required): Engage Sales / Coverage teams to:",
        agents: ["regulatory", "risk-scoring", "audit"] as AgentId[],
        agentLabel: "Stakeholder Escalation (if required)",
        postRunSummary: "Stakeholder Escalation (if required). Case status updated.",
        updates: [
          { attr: "Case Status", before: "Open · Pending analyst action", after: "Escalated" },
        ],
      },
    ],
  },
  {
    id: "gen2_2", title: "CIP Classification and NAICS code", confidence: 78, status: "Pending",
    entity: "BROOKFIELD ASSET MANAGEMENT PIC US, LLC", kyc: "KYC-30216", category: "Classification & Risk",
    flagText: "CIP classification: Internal classification and Nature of business trigger indicates financial activity flag due to industry code mapping (Source A · Form ADV) vs Client confirmed the entity should be classified as NFIE (Non-Financial Entity) (Source B - Client Confirmation).",
    narrative: "During onboarding the client confirmed the entity should be classified as **NFIE (Non-Financial Entity)**. However, an internal due diligence trigger has been raised due to the entity being mapped to Investment adviser / asset manager which is generally associated with **financial investment-related activities**. This creates a **classification discrepancy**, requiring confirmation on whether the entity should remain classified as **NFIE** or be reclassified as a **Financial Entity (Investment Entity)**.",
    reasoningSteps: [
      "The client has explicitly classified the entity as a Non-Financial Entity (NFIE), indicating that it does not consider itself to be engaged in regulated financial institution activities.",
      "The internal trigger is driven by the nature of business Investment adviser / asset manager, which is commonly linked to investment-related or financial activity, and therefore may indicate that the entity operates in a manner consistent with a Financial Entity / Investment Entity under KYC classification standards.",
      "The onboarding request further supports the need to assess whether the entity is functioning in a financial capacity, particularly if such activities extend beyond internal treasury or hedging purposes.",
      "While the nature of business describes the entity as a holding company / financing vehicle for group companies shared by the client, this needs to be validated to determine whether activities are strictly intra-group or extend to investment or financial services activity, which would change the classification outcome.",
    ],
    evidenceRationale: "Source A · Form ADV and Source B - Client Confirmation are the primary evidence sources.",
    evidence: [
      { name: "Source A · Form ADV", sub: "Internal classification and Nature of business trigger indic" },
      { name: "Source B - Client Confirmation", sub: "Client confirmed the entity should be classified as NFIE (No" },
    ],
    acceptability: "CIP Classification and NAICS code requires analyst review and resolution before case closure.",
    resolutions: [
      {
        id: "r1", title: "Request a Legal team review to assess", desc: "Request a Legal team review to assess the appropriateness of the client’s NFIE classification: Based on the nature of business (Investment adviser / asset manager), the entity’s access to derivatives trading products, and the possibility of investment-related activities, Legal is to evaluate whether the entity is more appropriately classified as a Financial Entity (Investment Entity / Financial Institution) and provide a documented position.",
        recommended: true,
        agents: ["regulatory", "risk-scoring", "audit"] as AgentId[],
        agentLabel: "Request a Legal team review to assess",
        postRunSummary: "Request a Legal team review to assess. Case status updated.",
        updates: [
          { attr: "Case Status", before: "Open · Pending analyst action", after: "In Progress" },
        ],
      },
      {
        id: "r2", title: "Targeted Client Outreach for Clarification", desc: "Targeted Client Outreach for Clarification: Conduct client outreach to validate the entity’s actual activities and support classification, specifically:",
        agents: ["regulatory", "risk-scoring", "audit"] as AgentId[],
        agentLabel: "Targeted Client Outreach for Clarification",
        postRunSummary: "Targeted Client Outreach for Clarification. Case status updated.",
        updates: [
          { attr: "Case Status", before: "Open · Pending analyst action", after: "Escalated" },
        ],
      },
      {
        id: "r3", title: "Use responses to substantiate classification as either", desc: "Use responses to substantiate classification as either Financial Entity or NFIE and ensure alignment with internal policy.",
        agents: ["regulatory", "risk-scoring", "audit"] as AgentId[],
        agentLabel: "Use responses to substantiate classification as either",
        postRunSummary: "Use responses to substantiate classification as either. Case status updated.",
        updates: [
          { attr: "Case Status", before: "Open · Pending analyst action", after: "Escalated" },
        ],
      },
    ],
  },
  {
    id: "gen2_3", title: "Acting Person", confidence: 85, status: "Pending",
    entity: "BROOKFIELD ASSET MANAGEMENT PIC US, LLC", kyc: "KYC-30216", category: "Beneficial Ownership",
    flagText: "Acting Person Classification: Acting Person identified, but not a member of Vorstand / Executive Management Board (Source A · Form ADV Schedule A) vs Policy states non-board Acting Persons must have documented authority (Power of Attorney or equivalent) (Source B · Client Submitted Documents).",
    narrative: "During KYC review, an **Acting Person (AP)** has been identified for the entity; however, the individual is **not a member of the Vorstand** (Executive Management Board) or equivalent governing body. As per the guidance, where the Acting Person is not part of the governing body, the individual must also be supported by documented authority, typically evidenced through a **Power of Attorney (PoA)** or inclusion in an authorized signatory list. In this case, no such supporting documentation has been provided, creating a gap in validating the individual’s authority to act on behalf of the entity. In the absence of such documentation, there is insufficient evidence to validate the individual’s authority, which presents a KYC control gap.",
    reasoningSteps: [
      "Guidance clearly states that Acting Persons who are not members of Vorstand (or equivalent senior governing authority) cannot rely solely on their designation and must have explicit delegated authority.",
      "The purpose of linking an individual as both Acting Person and Power of Attorney is to ensure there is legal evidence supporting their authority to represent the entity.",
      "Acceptable forms of such evidence include:",
    ],
    evidenceRationale: "Source A · Form ADV Schedule A and Source B · Client Submitted Documents are the primary evidence sources.",
    evidence: [
      { name: "Source A · Form ADV Schedule A", sub: "Acting Person identified, but not a member of Vorstand / Exe" },
      { name: "Source B · Client Submitted Documents", sub: "Policy states non-board Acting Persons must have documented " },
    ],
    acceptability: "Acting Person requires analyst review and resolution before case closure.",
    resolutions: [
      {
        id: "r1", title: "Client reach out requesting supporting Authority Documentation", desc: "Client reach out requesting supporting Authority Documentation: Reach out to the client to obtain a valid Power of Attorney (PoA) document confirming the individual’s authority, or an authorized signatory list clearly evidencing authorization. This will allow proper linkage of the individual as both Acting Person and authorized representative.",
        recommended: true,
        agents: ["beneficial-owner", "outreach", "audit"] as AgentId[],
        agentLabel: "Client reach out requesting supporting Authority Documentation",
        postRunSummary: "Client reach out requesting supporting Authority Documentation. Case status updated.",
        updates: [
          { attr: "Case Status", before: "Open · Pending analyst action", after: "In Progress" },
        ],
      },
      {
        id: "r2", title: "Revalidate Acting Person Selection", desc: "Revalidate Acting Person Selection: Request confirmation from the client on whether the identified Acting Person should be replaced with an individual who is part of the Vorstand / Executive Management Board, or if the current Acting Person remains valid but requires formal authority documentation.",
        agents: ["beneficial-owner", "outreach", "audit"] as AgentId[],
        agentLabel: "Revalidate Acting Person Selection",
        postRunSummary: "Revalidate Acting Person Selection. Case status updated.",
        updates: [
          { attr: "Case Status", before: "Open · Pending analyst action", after: "Escalated" },
        ],
      },
    ],
  },
];

export const GENERATED_COMPARISONS: Record<string, {
  aLabel: string; bLabel: string;
  rows: { field: string; a: string; b: string; conflict?: boolean }[];
}> = {
  "gen1_1": {
    aLabel: "Source A · Client Onboarding Form", bLabel: "Source B · SEC IAPD (Form ADV Part 1A)",
    rows: [
      { field: "US Registration Number", a: "801-12345 (self-reported)", b: "801-67890 (retrieved 2026-05-20)", conflict: true },
      { field: "Legal Entity Name", a: "Long Focus Capital Management, LLC", b: "Long Focus Capital Management, LLC" },
      { field: "Principal Address", a: "456 Broad Avenue, New York, NY", b: "456 Broad Avenue, New York, NY" },
    ],
  },
  "gen1_2": {
    aLabel: "Source A · GLEIF Registry", bLabel: "Source B · Client Onboarding Form",
    rows: [
      { field: "LEI Code", a: "No active LEI under entity legal name", b: "Not provided", conflict: true },
      { field: "Search by US Reg # 801-67890", a: "No match", b: "" },
      { field: "AUM (context)", a: "", b: "\\$2.4B reported" },
    ],
  },
  "gen1_3": {
    aLabel: "Source A · Corporate Website", bLabel: "Source B · Form ADV Filing (SEC)",
    rows: [
      { field: "Principal Address", a: "123 Main Street, New York, NY 10001", b: "456 Broad Avenue, New York, NY 10005", conflict: true },
      { field: "Source Date", a: "Retrieved 2026-05-20", b: "Filing dated 2026-03-31", conflict: true },
      { field: "Matches Client Form", a: "No", b: "Yes", conflict: true },
    ],
  },
  "gen1_4": {
    aLabel: "Source A · Form ADV Schedule A", bLabel: "Source B · Client Submitted Documents",
    rows: [
      { field: "Compliance Officer Name", a: "Sarah Chen (Chief Compliance Officer)", b: "Not listed", conflict: true },
      { field: "Signed Attestation", a: "", b: "Not provided" },
    ],
  },
  "gen1_5": {
    aLabel: "Source A · Form ADV Schedule A", bLabel: "Source B · Public Registry Traversal",
    rows: [
      { field: "25%+ Beneficial Owner", a: "Long Focus Holdings LLC (100%) — entity, not individual", b: "Chain terminates at Long Focus Holdings LLC; no further public data", conflict: true },
      { field: "FinCEN BOI Filing", a: "Not provided by client", b: "" },
      { field: "Companies House (UK branch)", a: "No PSC at >25%", b: "" },
    ],
  },
  "gen2_1": {
    aLabel: "Source A · Due Diligence", bLabel: "Source B · Internal records",
    rows: [
      { field: "Risk Rating", a: "High – Due to adding an optional field ownership country", b: "Low – Initial classification during the time of RR", conflict: true },
      { field: "Client Pushback", a: "Yes", b: "Yes" },
    ],
  },
  "gen2_2": {
    aLabel: "Source A · Form ADV", bLabel: "Source B - Client Confirmation",
    rows: [
      { field: "CIP classification", a: "Internal classification and Nature of business trigger indicates financial activity flag due to industry code mapping", b: "Client confirmed the entity should be classified as NFIE (Non-Financial Entity)", conflict: true },
      { field: "Nature of Business", a: "investment advisory services", b: "Indicates Holding company as per the nature of business shared", conflict: true },
      { field: "Client Pushback", a: "Client has provided responses and classification (no refusal)", b: "Client has provided responses and classification (no refusal)" },
    ],
  },
  "gen2_3": {
    aLabel: "Source A · Form ADV Schedule A", bLabel: "Source B · Client Submitted Documents",
    rows: [
      { field: "Acting Person Classification", a: "Acting Person identified, but not a member of Vorstand / Executive Management Board", b: "Policy states non-board Acting Persons must have documented authority (Power of Attorney or equivalent)", conflict: true },
      { field: "Power of Attorney (PoA) Evidence", a: "No PoA or authorized signatory evidence available", b: "PoA or equivalent documentation required to validate authority to act", conflict: true },
    ],
  },
};

export const GENERATED_ENTITY_PROFILES: Record<string, {
  name: string; kyc: string;
  attrs: { label: string; value: string; source: "CRM" | "3rd" | "Forge"; status: "ok" | "alert" | "warn" }[];
  caseFile: string;
}> = {
  "Long Focus Capital Management, LLC": {
    name: "Long Focus Capital Management, LLC", kyc: "KYC-30215",
    attrs: [
      { label: "Entity Name", value: "LONG FOCUS CAPITAL MANAGEMENT, LLC", source: "CRM", status: "ok" },
      { label: "Legal Entity Type", value: "Limited Liability Company", source: "CRM", status: "ok" },
      { label: "Country of Incorporation", value: "USA", source: "3rd", status: "ok" },
      { label: "Date of Incorporation", value: "5/10/2012", source: "3rd", status: "ok" },
      { label: "LEI Code", value: "[See Exception Details]", source: "3rd", status: "alert" },
      { label: "Trading Names", value: "Long Focus Capital", source: "CRM", status: "ok" },
      { label: "Previous Names", value: "Focus Capital Partners LLC", source: "CRM", status: "ok" },
      { label: "Verification of Existence", value: "Verified via Delaware State Registry", source: "3rd", status: "ok" },
      { label: "US Registration Number", value: "[See Exception Details]", source: "3rd", status: "alert" },
      { label: "Regulator", value: "SEC", source: "3rd", status: "ok" },
      { label: "Listing Status", value: "Not Listed", source: "3rd", status: "ok" },
      { label: "Entity GIIN", value: "987XYZ.654ABC.AB.123", source: "CRM", status: "ok" },
      { label: "SEC § 13/15(d) Indicator", value: "No", source: "CRM", status: "ok" },
      { label: "CFTC Registered Indicator", value: "No", source: "CRM", status: "ok" },
      { label: "Legal Registered Address", value: "1209 Orange Street, Wilmington, DE 19801, USA", source: "CRM", status: "ok" },
      { label: "Principal Place of Business", value: "[See Exception Details]", source: "CRM", status: "alert" },
      { label: "Website", value: "www.longfocuscapital.com", source: "CRM", status: "ok" },
      { label: "Foreign Branches", value: "UK Branch (FCA #123456)", source: "CRM", status: "ok" },
      { label: "Entity Classification", value: "RIA", source: "Forge", status: "ok" },
      { label: "Entity Risk Rating", value: "Medium", source: "Forge", status: "ok" },
      { label: "CIP Classification", value: "Legal Entity - LLC", source: "Forge", status: "ok" },
      { label: "Nature of Business", value: "Long/Short Equity Investment Management", source: "CRM", status: "ok" },
      { label: "Sole Proprietorship", value: "No", source: "CRM", status: "ok" },
      { label: "Parent Listed on US Exchange", value: "No", source: "CRM", status: "ok" },
      { label: "Other Business Activity", value: "None", source: "CRM", status: "ok" },
      { label: "Source of Funds", value: "Management Fees, Performance Fees", source: "CRM", status: "ok" },
      { label: "Source of Wealth", value: "Founder's Capital", source: "CRM", status: "ok" },
      { label: "Assets Under Management", value: "\\$2.4B", source: "CRM", status: "ok" },
      { label: "Transacting With", value: "Third Party Funds", source: "CRM", status: "ok" },
      { label: "US Tax ID", value: "98-7654321", source: "CRM", status: "ok" },
      { label: "Corporate Officer", value: "Michael J. Anderson (CEO)", source: "CRM", status: "ok" },
      { label: "Board Director", value: "Michael J. Anderson, Sarah K. Lee", source: "CRM", status: "ok" },
      { label: "Compliance Officer", value: "[See Exception Details]", source: "CRM", status: "alert" },
      { label: "Authorized Signatory", value: "Michael J. Anderson", source: "CRM", status: "ok" },
      { label: "Power of Attorney", value: "None on file", source: "CRM", status: "ok" },
      { label: "Key Controller", value: "Michael J. Anderson", source: "CRM", status: "ok" },
      { label: "Beneficial Owner (25%+)", value: "[See Exception Details]", source: "3rd", status: "alert" },
      { label: "List of Subsidiaries", value: "Long Focus UK Branch", source: "CRM", status: "ok" },
    ],
    caseFile: "# Long Focus Capital Management, LLC\n\n**KYC ID:** KYC-30215  \n**Entity Type:** Registered Investment Adviser (RIA)  \n**Jurisdiction:** United States \\  \n**Client Risk Rating:** High  \n**Open Exceptions:** 5\n\n## Entity Summary\nRegistered Investment Adviser (RIA) with 5 open exceptions requiring resolution.\n\n## Open Exceptions (5)\n1. **US Registration Number Mismatch** — US Registration Number: 801-12345 (self-reported) (Source A · Client Onboarding ....\n2. **Outstanding LEI Code** — LEI Code: No active LEI under entity legal name (Source A · GLEIF Registry) vs N....\n3. **Principal Place of Business Mismatch** — Principal Address: 123 Main Street, New York, NY 10001 (Source A · Corporate Web....\n4. **Missing Compliance Officer Attestation** — Compliance Officer Name: Sarah Chen (Chief Compliance Officer) (Source A · Form ....\n5. **Beneficial Ownership Not Identified** — 25%+ Beneficial Owner: Long Focus Holdings LLC (100%) — entity, not individual (....\n\n## Next Actions\n- Run SEC-ADV-Verification-Agent to confirm match, update the field to 801-67890, and log discrepancy ...\n- Request LEI from client via portal with templated outreach; defer with conditional approval if clien...\n- Accept Form ADV address (456 Broad Avenue) as authoritative; matches client form.",
  },
  "BROOKFIELD ASSET MANAGEMENT PIC US, LLC": {
    name: "BROOKFIELD ASSET MANAGEMENT PIC US, LLC", kyc: "KYC-30216",
    attrs: [
      { label: "Entity Name", value: "BROOKFIELD ASSET MANAGEMENT PIC US, LLC", source: "CRM", status: "ok" },
      { label: "Legal Entity Type", value: "Limited Liability Company", source: "CRM", status: "ok" },
      { label: "Country of Incorporation", value: "United States (Delaware)", source: "3rd", status: "ok" },
      { label: "Date of Incorporation", value: "22 July 2009", source: "3rd", status: "ok" },
      { label: "LEI Code", value: "549300FML6EDDNTAVG88", source: "3rd", status: "ok" },
      { label: "Trading Names", value: "BAM PIC US (commonly referenced)", source: "CRM", status: "ok" },
      { label: "Verification of Existence", value: "Active (SEC registered investment adviser + Delaware entity)", source: "3rd", status: "ok" },
      { label: "US Registration Number", value: "CRD: 151599 / SEC#: 801-72031", source: "3rd", status: "ok" },
      { label: "UK Registration Number", value: "Not applicable", source: "3rd", status: "ok" },
      { label: "Regulator", value: "U.S. SEC (registered investment adviser)", source: "3rd", status: "ok" },
      { label: "Listing Status", value: "Not listed (private LLC)", source: "3rd", status: "ok" },
      { label: "Listed Exchange", value: "Not applicable", source: "CRM", status: "ok" },
      { label: "SEC § 13/15(d) Indicator", value: "Not applicable", source: "CRM", status: "ok" },
      { label: "Legal Registered Address", value: "C/O Corporation Service Company, 251 Little Falls Drive, Wilmington, Delaware 19808, USA", source: "CRM", status: "ok" },
      { label: "Principal Place of Business", value: "Brookfield, 225 Liberty Street, 8th Floor, New York, NY 10281-1023, USA", source: "CRM", status: "ok" },
      { label: "Website", value: "<https://www.brookfield.com>", source: "CRM", status: "ok" },
      { label: "Entity Classification", value: "Investment adviser / asset manager", source: "Forge", status: "alert" },
      { label: "Entity Risk Rating", value: "Medium", source: "Forge", status: "alert" },
      { label: "CIP Classification", value: "Registered Investment Advisor", source: "Forge", status: "alert" },
      { label: "Nature of Business", value: "Provides investment advisory services to private funds, pooled vehicles, institutional accounts across real estate and alternative assets", source: "CRM", status: "ok" },
      { label: "Sole Proprietorship", value: "No", source: "CRM", status: "ok" },
      { label: "Parent Listed on US Exchange", value: "Yes", source: "CRM", status: "ok" },
      { label: "Other Business Activity", value: "Multi-sector alternative investments (real estate, infrastructure, energy, private equity)", source: "CRM", status: "ok" },
      { label: "Source of Funds", value: "Institutional investor capital (pooled vehicles, funds)", source: "CRM", status: "ok" },
      { label: "Source of Wealth", value: "Investment management earnings / fund structures", source: "CRM", status: "ok" },
      { label: "Assets Under Management", value: "~USD 105.3B (regulatory AUM, Dec 31 2025)", source: "CRM", status: "ok" },
      { label: "Transacting With", value: "Third-party client funds", source: "CRM", status: "ok" },
      { label: "UK Tax ID", value: "Not applicable", source: "CRM", status: "ok" },
      { label: "Acting Person", value: "", source: "CRM", status: "alert" },
      { label: "Sub-Advisor Name", value: "Fairfield Realty Advisors LLC, Thayer Lodging Group LLC", source: "CRM", status: "ok" },
      { label: "Key Controller", value: "Brookfield Asset Management group", source: "CRM", status: "ok" },
      { label: "Beneficial Owner (25%+)", value: "Brookfield Asset Management group", source: "3rd", status: "ok" },
      { label: "Trustee", value: "Not applicable", source: "CRM", status: "ok" },
    ],
    caseFile: "# BROOKFIELD ASSET MANAGEMENT PIC US, LLC\n\n**KYC ID:** KYC-30216  \n**Entity Type:** Registered Investment Adviser (RIA)  \n**Jurisdiction:** US (Delaware) with UK branch  \n**Client Risk Rating:** Low  \n**Open Exceptions:** 3\n\n## Entity Summary\nRegistered Investment Adviser (RIA) with 3 open exceptions requiring resolution.\n\n## Open Exceptions (3)\n1. **Risk Rating** — Risk Rating: High – Due to adding an optional field ownership country (Source A ....\n2. **CIP Classification and NAICS code** — CIP classification: Internal classification and Nature of business trigger indic....\n3. **Acting Person** — Acting Person Classification: Acting Person identified, but not a member of Vors....\n\n## Next Actions\n- Threshold Alignment: Seek confirmation from Compliance to proceed with a 25% ownership drilldown thr...\n- Request a Legal team review to assess the appropriateness of the client’s NFIE classification: Based...\n- Client reach out requesting supporting Authority Documentation: Reach out to the client to obtain a ...",
  },
};

export const GENERATED_ENTITY_GROUPS: Record<string, { drg: string; attrs: string[] }> = {
  "Long Focus Capital Management, LLC": { drg: "US Private Equity DRG", attrs: ["LEI Code", "US Registration Number", "Principal Place of Business", "Compliance Officer"] },
  "BROOKFIELD ASSET MANAGEMENT PIC US, LLC": { drg: "US Private Equity DRG", attrs: ["Entity Classification", "Entity Risk Rating", "CIP Classification", "Acting Person"] },
};

export const GENERATED_ENTITY_DRG: Record<string, string> = {
  "KYC-30215": "US Private Equity DRG",
  "KYC-30216": "US Private Equity DRG",
};

export const GENERATED_WORK_ROWS: {
  id: string; name: string; kyc: string; due: string; confidence: string;
  customerType: string; jurisdiction: string;
  priority: "Low" | "Medium" | "High";
  risk: "Minimal" | "Moderate" | "Elevated";
  exc: number; status: "In Progress"; action: "Periodic Refresh"; selectable: true;
}[] = [
  {
    id: "gen1", name: "Long Focus Capital Management, LLC", kyc: "KYC-30215",
    due: "Jul 15, 2026", confidence: "91%",
    customerType: "Registered Investment Adviser (RIA)", jurisdiction: "United States \\",
    priority: "High",
    risk: "Elevated",
    exc: 5, status: "In Progress", action: "Periodic Refresh", selectable: true,
  },
  {
    id: "gen2", name: "BROOKFIELD ASSET MANAGEMENT PIC US, LLC", kyc: "KYC-30216",
    due: "Jul 22, 2026", confidence: "91%",
    customerType: "Registered Investment Adviser (RIA)", jurisdiction: "US (Delaware) with UK branch",
    priority: "Low",
    risk: "Minimal",
    exc: 3, status: "In Progress", action: "Periodic Refresh", selectable: true,
  },
];

export const GENERATED_DASHBOARD_CASES: {
  priority: "High" | "Medium" | "Low"; id: string; entity: string;
  note: string; due: string; est: string; status: "open";
}[] = [
  { priority: "High", id: "KYC-30215", entity: "Long Focus Capital Management, LLC",
    note: "US Registration Number Mismatch — US Registration Number: 801-12345 (self-reported) (Source A · Client Onboarding Form) ", due: "Jul 15", est: "45 min", status: "open" },
  { priority: "Low", id: "KYC-30216", entity: "BROOKFIELD ASSET MANAGEMENT PIC US, LLC",
    note: "Risk Rating — Risk Rating: High – Due to adding an optional field ownership country (Source A · Due Diligence) vs Low – ", due: "Jul 15", est: "30 min", status: "open" },
];

export const GENERATED_COMMENTS: Record<string, {
  author: string; initials: string; role: string; time: string;
  kind: "comment" | "ai" | "action"; body: string;
}[]> = {
  "KYC-30215": [
    { author: "AI Agent", initials: "AI", role: "Automated Review", time: "Today",
      kind: "ai", body: "5 exceptions detected. Top priority: US Registration Number Mismatch." },
  ],
  "KYC-30216": [
    { author: "AI Agent", initials: "AI", role: "Automated Review", time: "Today",
      kind: "ai", body: "3 exceptions detected. Top priority: Risk Rating." },
  ],
};

export const GENERATED_TASKS: Record<string, {
  title: string; assignee: string; due: string; status: "Open" | "In Progress" | "Done";
}[]> = {
  "KYC-30215": [
    { title: "Resolve: US Registration Number Mismatch", assignee: "Unassigned", due: "TBD", status: "Open" },
    { title: "Resolve: Outstanding LEI Code", assignee: "Unassigned", due: "TBD", status: "Open" },
    { title: "Resolve: Principal Place of Business Mismatch", assignee: "Unassigned", due: "TBD", status: "Open" },
  ],
  "KYC-30216": [
    { title: "Resolve: Risk Rating", assignee: "Unassigned", due: "TBD", status: "Open" },
    { title: "Resolve: CIP Classification and NAICS code", assignee: "Unassigned", due: "TBD", status: "Open" },
    { title: "Resolve: Acting Person", assignee: "Unassigned", due: "TBD", status: "Open" },
  ],
};

export const GENERATED_WATCHERS: Record<string, {
  name: string; initials: string; role: string;
}[]> = {
  "KYC-30215": [
    { name: "Priya Patel", initials: "PP", role: "KYC Analyst · L1" },
    { name: "Quinn Doe",   initials: "QD", role: "Reviewer · L2" },
  ],
  "KYC-30216": [
    { name: "Priya Patel", initials: "PP", role: "KYC Analyst · L1" },
    { name: "Quinn Doe",   initials: "QD", role: "Reviewer · L2" },
  ],
};

export const GENERATED_ACTIVITY: Record<string, { time: string; text: string }[]> = {
  "KYC-30215": [
    { time: "Today", text: "Case opened from entities.md" },
    { time: "Today", text: "AI Agent flagged 5 exceptions during initial review" },
  ],
  "KYC-30216": [
    { time: "Today", text: "Case opened from entities.md" },
    { time: "Today", text: "AI Agent flagged 3 exceptions during initial review" },
  ],
};
